version: '3'
services:
  webpacker:
    build:
      args:
        - RAILS_ROOT=/${APP_NAME}
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    command: ./bin/webpack-dev-server
    volumes:
      - .:/${APP_NAME}
    ports:
      - '3035:3035'
  db:
    image: postgres:11.1
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: "${APP_NAME}_${RAILS_ENV}"
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASS
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5434:5432
  app:
    build:
      args:
        - RAILS_ROOT=/${APP_NAME}
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: ["bundle","exec","rails","s", "-b", "0.0.0.0"]
    container_name: app
    environment:
      DB_USER: $POSTGRES_USER
      DB_PASSWORD: $POSTGRES_PASS
      DB_NAME: "${APP_NAME}_${RAILS_ENV}"
    volumes:
      - .:/${APP_NAME}
    ports:
      - 3000:3000

volumes:
  dbdata:
    driver: local